/*

 BUTTONS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define buttonsBank 0

/* Super Gameboy palette 0 */
#define buttonsSGBPal0c0 6076
#define buttonsSGBPal0c1 8935
#define buttonsSGBPal0c2 6596
#define buttonsSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define buttonsSGBPal1c0 6076
#define buttonsSGBPal1c1 8935
#define buttonsSGBPal1c2 6596
#define buttonsSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define buttonsSGBPal2c0 6076
#define buttonsSGBPal2c1 8935
#define buttonsSGBPal2c2 6596
#define buttonsSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define buttonsSGBPal3c0 6076
#define buttonsSGBPal3c1 8935
#define buttonsSGBPal3c2 6596
#define buttonsSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define buttonsCGBPal0c0 6076
#define buttonsCGBPal0c1 8935
#define buttonsCGBPal0c2 6596
#define buttonsCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define buttonsCGBPal1c0 6076
#define buttonsCGBPal1c1 8935
#define buttonsCGBPal1c2 6596
#define buttonsCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define buttonsCGBPal2c0 6076
#define buttonsCGBPal2c1 8935
#define buttonsCGBPal2c2 6596
#define buttonsCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define buttonsCGBPal3c0 6076
#define buttonsCGBPal3c1 8935
#define buttonsCGBPal3c2 6596
#define buttonsCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define buttonsCGBPal4c0 6076
#define buttonsCGBPal4c1 8935
#define buttonsCGBPal4c2 6596
#define buttonsCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define buttonsCGBPal5c0 6076
#define buttonsCGBPal5c1 8935
#define buttonsCGBPal5c2 6596
#define buttonsCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define buttonsCGBPal6c0 6076
#define buttonsCGBPal6c1 8935
#define buttonsCGBPal6c2 6596
#define buttonsCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define buttonsCGBPal7c0 6076
#define buttonsCGBPal7c1 8935
#define buttonsCGBPal7c2 6596
#define buttonsCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char buttons[];

/* End of BUTTONS.H */
